name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]  # 可根据需要添加其他架构

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build project
        run: go build

    outputs:
      binary_path: ${{ steps.build.outputs.binary_path }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build project
        run: go build

      - name: Create release
        uses: actions/create-release@v1
        with:
          files: |
            ${{ needs.build.outputs.binary_path }}/*

          token: ${{ secrets.GITHUB_TOKEN }}
